{
  "hash": "5b66b53cf704f7c9d6d7977fe8aab5e8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: A cross-sectional observational study on the impact of cost on cardiac events in adults using simulated data\nauthors: \n  - name: Tracy Chidyausiku\n    affiliation: Stanford University\n    roles: conception, study design, analysis, writing and editing\n    corresponding: true\nbibliography: references.bib\n---\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(here)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nhere() starts at /Users/tracychidyausiku/Coursework/epi/epi203/EPI203_Assignment4_ReproducibleReport\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(tinytex)\nlibrary(table1)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'table1'\n\nThe following objects are masked from 'package:base':\n\n    units, units<-\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(kableExtra)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(webshot2)\nlibrary(gtsummary)\nlibrary(modelsummary)\nlibrary(broom.helpers)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'broom.helpers'\n\nThe following objects are masked from 'package:gtsummary':\n\n    all_categorical, all_continuous, all_contrasts, all_dichotomous,\n    all_interaction, all_intercepts\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(forrest)\nlibrary(magick)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLinking to ImageMagick 6.9.13.29\nEnabled features: cairo, fontconfig, freetype, heic, lcms, pango, raw, rsvg, webp\nDisabled features: fftw, ghostscript, x11\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nlibrary(ggplot2)\n```\n:::\n\n\n## Introduction\n\nIn the United States, the overwhelming majority of adults experiencing cardiac events fall disproportionately on individuals experiencing poverty (low to very low income) on the county and federal levels. Cardiac events are closely linked with ongoing cardiovascular diseases in patients and are the leading cause of death in the United States. As a result, rates in cardiovascular disease and death in low to very low income individuals have increased at an alarming rate in recent years and are only expected to more than triple in the next five years. To better understand the social mechanisms, primarily financial factors like medical costs, that impact an individual's ability to prevent or delay cardiac events we used synthetic data to measure how cost influences cardiac events.\n\nThe study objective is to measure how cost of care influences cardiac events in the presence of controlling for biological and social factors including age, sex, and smoking. We hypothesize that higher medical costs are associated with an increase in cardiac events when controlling for age, sex, and smoking.\n\n## Methods\n\nA cross-sectional study using synthetic data from the Department of Health Policy at Stanford University was conducted to investigate how medical costs impact cardiac events in adult patients.\n\n### Dataset\n\nData was used from a synthetic data set created by the Health Policy Department at Stanford University (Sherri Rose, PhD). The data are synthetic and developed in 2026 trained using de-identified health data from a national dataset of adult (18 years and older) cardiac hospitalizations in the United States from 2025. The synthetic dataset is publicly accessible (<https://github.com/MethodsForReproducibleHealthResearch/Assignment2>). The dataset contains 5,000 synthetic adult health records with variables including medical costs, cardiac events, sex, age, and smoking status.\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n#| include: false\n\n# load dataset\nsynthetic_df <- read_csv(here(\"raw-data\", \"cohort.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 5000 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (5): smoke, female, age, cardiac, cost\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\n# check for any missingness\nsum(is.na(synthetic_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\n# visualize distribution of continuous variables\nhist(synthetic_df$age)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/load libraries and dataset-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\nhist(synthetic_df$cost)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/load libraries and dataset-2.png){width=672}\n:::\n:::\n\n\n### Study Population\n\nThe synthetic data consists of a 5,000 observations with no missing data. The dataset was evaluated in its entirety, with no exclusions based on outliers or key variables for a complete-case analysis. The final analysis included all 5,000 observations originally developed synthetically in the dataset.\n\n### Study Variables and Outcome\n\nCardiac events may include any sudden, serious problem impacting the cardiovascular system, particularly the heart. All synthetic data were developed based on the data collection and observations in a national dataset of adult (18 years and older) cardiac hospitalizations in the United States from 2025. Based on the national dataset, cardiac events were pre-defined and measured in the dataset as a binary variable (e.g., yes or no if a cardiac event was observed in the patient) based on ICD-9 and ICD-10 codes coded by the care team or hospital. In this study, the dependent variable was cardiac events and was measured using the synthetic dataset's pre-defined and measured reports as stated above. The primary independent variable in this study was medical costs. Based on the national dataset, medical costs were collected and measured in the dataset for each observation. Medical costs were calculated by the hospital billing team based on the type of care received given the particular cardiac event experienced by the patient at the point-of-care and time received. Potential confounders include sex, age, and gender. All potential confounders were self-reported by patients for hospital system record collections and are routinely collected during admission to hospital stays or to receive care.\n\nBiological and behavioral health factors (sex, age, smoking) were selected a priori based on prior research and established causal diagrams in literature showing the association and influence of these factors on financial factors and cardiac events. All study variables were assessed in their original, individual item level. No variables were combined into composite indices, nor were any continuous variables transformed into categorical groupings. We assessed biases such as selection bias in the dependent, independent, and potential confounders using Pearson's Chi-squared test and Wilcoxon rank sum test and visually assessed spread of potential confounders using histograms.\n\n### Statistical Analysis\n\nWe used logistic regression (using R's *stats* built-in package) to evaluate the odds ratios and 95% confidence intervals (CI) for the relationship between medical costs and cardiac events controlling for sex, age, and smoking. Reference groups for categorical variables sex and smoking include male and non-smoker, respectively. Logistic regression is a classification algorithm that models the log-odds of an event occurring by optimizing coefficients using maximum likelihood estimation. The logistic regression hypothesis is modeled by predictors $x$ and coefficients $\\theta$: $$h_{\\theta} = \\frac{1}{1 + e^{-\\theta^Tx}}$$\n\nFor this study, our logistic regression equation was modeled with cardiac event (yes or no) as the dependent variable and medical cost as the primary independent variable. To control for confounding, our model also adjusted for sex, age, and smoking. Specifically, let $Y$ represent a given outcome for an individual $i$:\n\n$$Y_i = \\alpha + \\beta_1Cost_{1,i} + \\beta_2Sex_{2,i} + \\beta_3Smoke_{3,i} + \\beta_4Age_{4,i}$$\n\n$Cost$ is the indicator for medical cost related to the observed cardiac event, $Sex$ is an indicator for the self-reported sex (male or female) by the individual, $Smoke$ is the indicator for the self-reported smoking status of the patient when the data were collected, and $Age$ is the self-reported age of the patient. Each indicator is calculated for every individual $i$ in the dataset. All analyses were performed in RStudio (Version 2026.04.0+526).\n\n## Results\n\n### Population Demographics\n\nAmong the 5,000 individuals in our study, the majority of participants self-reported as non-smokers (N = 4,354, 87%), female (N = 2,866, 57%) and had an average age of 45 and average medical cost of \\$9,376. In the overal study population, we observed an unequal balance in self-reported smoking, but a generally balanced self-report in sex (Table 1). Potential confounders smoke, sex, and cost were statistically significant with p \\< 0.001. Age groups between those who experienced cardiac events and did not experience cardiac events were similar interquartile ranges and thus a p=0.11.\n\n\n::: {#tbl-patients .cell tbl-cap='Patient Characteristics'}\n\n```{.r .cell-code .hidden}\n#| label: tbl-patients\n#| tbl-cap: \"Patient Characteristics\"\n\n# Make binary variables factors\nsynthetic_df$female <- factor(synthetic_df$female, levels=c(0,1), labels=c(\"Male\", \"Female\"))\nsynthetic_df$smoke <- factor(synthetic_df$smoke, levels=c(0,1), labels=c(\"No Smoke\", \"Smoke\"))\nsynthetic_df$cardiac <- factor(synthetic_df$cardiac, levels=c(0,1), labels=c(\"No Cardiac\", \"Cardiac\"))\n\n# Create table labels\nlabel(synthetic_df$female) <- \"Sex\"\nlabel(synthetic_df$smoke) <- \"Smoke\"\nlabel(synthetic_df$cost) <- \"Cost\"\nlabel(synthetic_df$age) <- \"Age\"\n\n# create table 1\nsynthetic_df %>% \n  tbl_summary(by = cardiac) %>% \n  add_p() %>% \n  add_overall() %>% \n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zwfcobstjd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zwfcobstjd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zwfcobstjd thead, #zwfcobstjd tbody, #zwfcobstjd tfoot, #zwfcobstjd tr, #zwfcobstjd td, #zwfcobstjd th {\n  border-style: none;\n}\n\n#zwfcobstjd p {\n  margin: 0;\n  padding: 0;\n}\n\n#zwfcobstjd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zwfcobstjd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zwfcobstjd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zwfcobstjd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zwfcobstjd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zwfcobstjd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zwfcobstjd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zwfcobstjd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zwfcobstjd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zwfcobstjd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zwfcobstjd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zwfcobstjd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zwfcobstjd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zwfcobstjd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zwfcobstjd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zwfcobstjd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zwfcobstjd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zwfcobstjd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zwfcobstjd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zwfcobstjd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zwfcobstjd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zwfcobstjd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zwfcobstjd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zwfcobstjd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zwfcobstjd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zwfcobstjd .gt_left {\n  text-align: left;\n}\n\n#zwfcobstjd .gt_center {\n  text-align: center;\n}\n\n#zwfcobstjd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zwfcobstjd .gt_font_normal {\n  font-weight: normal;\n}\n\n#zwfcobstjd .gt_font_bold {\n  font-weight: bold;\n}\n\n#zwfcobstjd .gt_font_italic {\n  font-style: italic;\n}\n\n#zwfcobstjd .gt_super {\n  font-size: 65%;\n}\n\n#zwfcobstjd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zwfcobstjd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zwfcobstjd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zwfcobstjd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zwfcobstjd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zwfcobstjd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zwfcobstjd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zwfcobstjd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zwfcobstjd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNSwwMDA=\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 5,000</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipObyBDYXJkaWFjKiogIApOID0gNCw3MjU=\"><span class='gt_from_md'><strong>No Cardiac</strong><br />\nN = 4,725</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipDYXJkaWFjKiogIApOID0gMjc1\"><span class='gt_from_md'><strong>Cardiac</strong><br />\nN = 275</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Smoke</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No Smoke</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,354 (87%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4,212 (89%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">142 (52%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Smoke</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">646 (13%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">513 (11%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">133 (48%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,134 (43%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,892 (40%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">242 (88%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,866 (57%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,833 (60%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">33 (12%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Age</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">45 (31, 59)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">45 (31, 59)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">47 (31, 61)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.11</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Cost</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">9,376 (9,090, 9,676)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">9,350 (9,072, 9,622)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">10,230 (9,910, 10,506)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk7IE1lZGlhbiAoUTEsIFEzKQ==\"><span class='gt_from_md'>n (%); Median (Q1, Q3)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"UGVhcnNvbidzIENoaS1zcXVhcmVkIHRlc3Q7IFdpbGNveG9uIHJhbmsgc3VtIHRlc3Q=\"><span class='gt_from_md'>Pearson’s Chi-squared test; Wilcoxon rank sum test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe study population was mostly imbalanced across those who did and did not experience cardiac events. For example, among individuals who did not experience a cardiac event 87% were non-smokers compared to 13%. Similarly, among individuals who did experience a cardiac event 88% were men and 12% were women. Individuals who experienced a cardiac event had an average medical cost of \\$10,230 compared to an average medical cost of \\$9,350 among individuals who did not experience a cardiac event. This resulted in an absolute difference of \\$880 between the two groups, which depending on socioeconomic factors can be a significant difference. We also observed a steady positive trend in cost by age in individuals who experienced a cardiac event during our study period (Figure 1).\n\n\n::: {#cell-fig-cost-trend .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\n#| label: fig-cost-trend\n#| fig-cap: \"Cost Trend by Age Among Individuals with Cardiac Events\"\n#| fig-width: 5\n#| fig-height: 3\n#| fig-align: center\n\n# dataframe including only those with cardiac events\ncardiac_df <- synthetic_df %>% \n  filter(cardiac == \"Cardiac\", smoke == \"Smoke\")\n\ntrend_plot <- ggplot(cardiac_df, aes(x = age, y = cost)) +\n  geom_point(color = \"darkblue\", size = 2) +          \n  geom_smooth(\n    method = \"loess\",                                  \n    se = FALSE,                                        \n    color = \"royalblue\", \n    linewidth = 1\n  ) +\n  labs(x = \"Age (Years)\", y = \"Medical Cost ($)\") +\n  theme (plot.caption = element_text(hjust = 0, face = \"bold\", size = 10))\n\n# save line graph plot to working directory\nggsave(\"trend_plot.png\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving 5 x 3 in image\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-cost-trend\n#| fig-cap: \"Cost Trend by Age Among Individuals with Cardiac Events\"\n#| fig-width: 5\n#| fig-height: 3\n#| fig-align: center\n\n# include trend plot image into manuscript\nknitr::include_graphics(here(\"trend_plot.png\"))\n```\n\n::: {.cell-output-display}\n![Cost Trend by Age Among Individuals with Cardiac Events](../trend_plot.png){#fig-cost-trend fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n#| include: false\n\n# logistic regression analysis - crude model\n# model: logistic regression\nlogistic_crude <- glm(cardiac ~ cost, data = synthetic_df, family = \"binomial\")\nsummary(logistic_crude)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cardiac ~ cost, family = \"binomial\", data = synthetic_df)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -5.242e+01  2.326e+00  -22.54   <2e-16 ***\ncost         5.071e-03  2.324e-04   21.82   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2129.8  on 4999  degrees of freedom\nResidual deviance: 1178.6  on 4998  degrees of freedom\nAIC: 1182.6\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| include: false\n\n# logistic regression analysis - adjusted model for age, smoking, gender\nlogistic_adjusted <- glm(cardiac ~ cost + female + smoke + age, data = synthetic_df, family = \"binomial\")\nsummary(logistic_adjusted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cardiac ~ cost + female + smoke + age, family = \"binomial\", \n    data = synthetic_df)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -9.472e+01  4.954e+00 -19.119   <2e-16 ***\ncost          1.023e-02  5.442e-04  18.808   <2e-16 ***\nfemaleFemale  2.989e-01  2.615e-01   1.143    0.253    \nsmokeSmoke   -3.037e+00  3.094e-01  -9.815   <2e-16 ***\nage          -1.637e-01  1.101e-02 -14.875   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2129.82  on 4999  degrees of freedom\nResidual deviance:  782.31  on 4995  degrees of freedom\nAIC: 792.31\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\n### Prevalence and Odds Ratios for Cardiac Event\n\nIn this study population, the overall prevalence of a cardiac event was 5.5% (N = 275). Of the individuals who did experience a cardiac event, 52% (N = 142) self-reported as ever smokers and 88% (N = 242) were male. The average age of those who experienced a cardiac event was 47 years and the average medical cost was \\$10,230 (Table 1).\n\n\n::: {#tbl-outcomes .cell tbl-cap='Multivariable logistic regression of cost and cardiac events adjusted for sex, smoke, and age.'}\n\n```{.r .cell-code .hidden}\n#| label: tbl-outcomes\n#| tbl-cap: \"Multivariable logistic regression of cost and cardiac events adjusted for sex, smoke, and age.\"\n\n# create table 2 separately for crude and adjusted models in order to later merge\ntable2_adjusted <- logistic_adjusted %>% \n  tbl_regression(exponentiate = TRUE) %>% \n  bold_p() %>% \n  add_global_p() %>% \n  italicize_levels()\n\ntable2_adjusted\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xucnvxtadn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xucnvxtadn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xucnvxtadn thead, #xucnvxtadn tbody, #xucnvxtadn tfoot, #xucnvxtadn tr, #xucnvxtadn td, #xucnvxtadn th {\n  border-style: none;\n}\n\n#xucnvxtadn p {\n  margin: 0;\n  padding: 0;\n}\n\n#xucnvxtadn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xucnvxtadn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xucnvxtadn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xucnvxtadn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xucnvxtadn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xucnvxtadn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xucnvxtadn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xucnvxtadn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xucnvxtadn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xucnvxtadn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xucnvxtadn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xucnvxtadn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xucnvxtadn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xucnvxtadn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xucnvxtadn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xucnvxtadn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xucnvxtadn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xucnvxtadn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xucnvxtadn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xucnvxtadn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xucnvxtadn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xucnvxtadn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xucnvxtadn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xucnvxtadn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xucnvxtadn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xucnvxtadn .gt_left {\n  text-align: left;\n}\n\n#xucnvxtadn .gt_center {\n  text-align: center;\n}\n\n#xucnvxtadn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xucnvxtadn .gt_font_normal {\n  font-weight: normal;\n}\n\n#xucnvxtadn .gt_font_bold {\n  font-weight: bold;\n}\n\n#xucnvxtadn .gt_font_italic {\n  font-style: italic;\n}\n\n#xucnvxtadn .gt_super {\n  font-size: 65%;\n}\n\n#xucnvxtadn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xucnvxtadn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xucnvxtadn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xucnvxtadn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xucnvxtadn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xucnvxtadn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xucnvxtadn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xucnvxtadn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xucnvxtadn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Cost</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.01</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.01, 1.01</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.3</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.35</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.80, 2.24</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Smoke</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    No Smoke</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Smoke</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.05</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.03, 0.09</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.85</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.83, 0.87</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nIn our adjusted logistic regression model, we observed a 1% increase in odds for a cardiac event (OR: 1.01, 95% CI: 1.01, 1.01) for every \\$1 increase in cost (Table 2). Additionally, for two key confounders, we observed a significant finding in increased odds: individuals who self-reported having ever smoked had 95% lower odds of a cardiac event compared to non-smokers and each increase in year in age was associated with 15% lower odds of a cardiac event. Lastly, we observed a 35% increase in odds for a cardiac event in females compared to males, but the confidence interval included the null (Figure 2).\n\n\n::: {#cell-fig-forest-plot .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\n#| label: fig-forest-plot\n#| fig-cap: \"Adjusted odds ratios of cost and cardiac events adjusted for sex, smoke, and age.\"\n#| fig-width: 5\n#| fig-height: 3\n#| fig-align: center\n\ncoefs <- tidy(logistic_adjusted, exponentiate = TRUE, conf.int = TRUE)\ncoefs <- coefs[coefs$term != \"(Intercept)\", ]\ncoefs$term <- c(\"Cost\", \"Sex\", \"Smoke\", \"Age\")\n\ncoefs$coef_ci <- sprintf(\n  \"%.2f (%.2f, %.2f)\",\n  coefs$estimate, coefs$conf.low, coefs$conf.high\n)\n\n# create and save forrest plot as .png\nsave_forrest(\"forrest_plot.png\", function() {\n  forrest(\n  coefs,\n  estimate = \"estimate\",\n  lower = \"conf.low\",\n  upper = \"conf.high\",\n  label = \"term\",\n  header = \"Predictor\",\n  cols     = c(\"OR (95% CI)\" = \"coef_ci\"),\n  widths   = c(3, 4, 2.5),\n  xlab     = \"Odds Ratio (95% CI)\",\n  stripe   = TRUE,\n  ref_line = 1\n)\n}, width = 5, height = 3, dpi = 300, bg = \"white\")\n\n# include forest plot image into manuscript\nknitr::include_graphics(here(\"forrest_plot.png\"))\n```\n\n::: {.cell-output-display}\n![Adjusted odds ratios of cost and cardiac events adjusted for sex, smoke, and age.](../forrest_plot.png){#fig-forest-plot fig-align='center'}\n:::\n:::\n\n\n## Discussion\n\nIn this study, we found that cost is associated with an increase in odds for cardiac events. Biological and behavioral health factors were associated with the relationship of interest; specifically, sex and identifying as female were associated with increased odds in experiencing a cardiac event and smoking was associated with lower odds of experiencing a cardiac event. Our finding that smoking was associated with lower odds of cardiac events is counter to current literature which has strongly established a causal relationship in smoking increasing the risk for cardiac events. We believe that our findings that smoking is protective (OR = 0.05, CI = 0.03, 0.09) may be driven by the imbalance in smoking and rates of cardiac events in females compared to males who make up 88% of cardiac events in our study. Additionally, the contractual findings we observed compared to literature may also be driven by inherent differences in our synthetic dataset compared to real-world data from electronic health records or claims data. Moving forward, we will seek to perform this study on electronic health records to validate our findings in this study.\n\nWe also acknowledge that our study is not without limitations. First, this study used synthetic data that may not accurately reflect the true prevalence of the variables, nor characteristics of the study population. Future studies should seek to use non-synthetic data to validate these findings. Secondly, the prevalence of cardiac events in this study population was rare, which may have the potential to introduce statistical bias or generous significance levels. However, given the ability to interpret the odds ratio as risk ratio in rare outcomes, we pursued the use of logistic regression despite the 5.5% prevalence of cardiac events in our study population. Lastly, we observed extreme class imbalance between cardiac events in men and women, with men experiencing the majority of cardiac events.\n\nIn summary, our findings suggest an association between cost and cardiac events controlling for biological and behavioral health factors further adding evidence of the influence economic factors have on health, particularly cardiovascular diseases and hospitalizations.\n\n## Generative AI Statement\n\nAll work, graphics/visuals, writing, study design, data analysis, and work to produce this manuscript was completed without the use of generative AI technology (e.g., ChatGPT).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}